#!/usr/bin/env bash
# Generate all per-instance random flags and secrets files.
# Called by spin-up.sh. Writes to secrets/ under the repo root.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# First arg: target secrets dir. Defaults to secrets/default for backwards
# compatibility with the single-instance workflow.
SECRETS_DIR="${1:-$REPO_ROOT/secrets/default}"
case "$SECRETS_DIR" in
  /*) ;;
  *)  SECRETS_DIR="$REPO_ROOT/$SECRETS_DIR" ;;
esac

# shellcheck source=./lib/random.sh
source "$SCRIPT_DIR/lib/random.sh"

mkdir -p "$SECRETS_DIR"

# ------------------------------------------------------------------------------
# Task 04 plaintext drives several other tasks — generate it first.
# ------------------------------------------------------------------------------
FLAG_TASK04_PLAINTEXT="$(rand_pronounceable)"
FLAG_TASK03_B64="$(b64_encode "$FLAG_TASK04_PLAINTEXT")"

# Task 06 DNS hostname: h-<first 8 hex of sha256(plaintext)>.internal.ctf
_sha_full="$(sha256_hex "$FLAG_TASK04_PLAINTEXT")"
FLAG_TASK06_HOST="h-${_sha_full:0:8}.internal.ctf"
FLAG_TASK06_TXT="$(rand_hex 24)"

# Task 08 auth token == task 04 plaintext
FLAG_TASK08_AUTH_TOKEN="$FLAG_TASK04_PLAINTEXT"
FLAG_TASK08_SECRET="$(rand_hex 20)"

# ------------------------------------------------------------------------------
# Independent per-task flags
# ------------------------------------------------------------------------------
FLAG_TASK02_PORT="$(rand_port 1024 65000)"
while [ "$FLAG_TASK02_PORT" = "2222" ] || [ "$FLAG_TASK02_PORT" = "22" ]; do
  FLAG_TASK02_PORT="$(rand_port 1024 65000)"
done

FLAG_TASK05_SSH_PASS="$(rand_triple)"
FLAG_TASK05_FILE="$(rand_hex 16)"

FLAG_TASK07_TX="TX-$(rand_hex 6)"

# ------------------------------------------------------------------------------
# Task 09: XOR crypto — choose plaintext, generate key, compute ciphertext
# ------------------------------------------------------------------------------
FLAG_TASK09_PLAINTEXT="$(rand_sentence)"
_pt_hex="$(ascii_to_hex "$FLAG_TASK09_PLAINTEXT")"
_pt_len=${#_pt_hex}
FLAG_TASK09_KEY="$(rand_hex "$_pt_len")"
FLAG_TASK09_CIPHERTEXT="$(xor_hex "$_pt_hex" "$FLAG_TASK09_KEY")"

# ------------------------------------------------------------------------------
# Task 01: answer is the sorted CSV of DECOY hostnames. The target set is
# fixed (mercury, venus, earth-logs, mars-hop, jupiter-api, saturn-crypto,
# neptune-final — the eight planets, give or take Earth as "earth-logs") but
# we pick 3–5 random decoys from a pool of moons + dwarf planets and actually
# run them via docker-compose.override.yml, so the answer genuinely varies
# across instances.
# ------------------------------------------------------------------------------
DECOY_POOL=(luna titan europa io callisto phobos deimos ganymede charon ceres pluto eris)
_decoy_count=$(( (RANDOM % 3) + 3 ))
_decoys_csv=$(printf '%s\n' "${DECOY_POOL[@]}" | awk 'BEGIN{srand()} {print rand() "\t" $0}' | sort -k1,1n | head -n "$_decoy_count" | cut -f2- | sort | tr '\n' ',' | sed 's/,$//')
DECOY_NAMES="$_decoys_csv"
DECOY_COUNT="$_decoy_count"

FLAG_TASK01="$DECOY_NAMES"

# ------------------------------------------------------------------------------
# Task 10: expected sha256 over all previous flags, joined with \n in canonical order
# ------------------------------------------------------------------------------
_flags_concat=$(printf '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s' \
  "$FLAG_TASK01" \
  "$FLAG_TASK02_PORT" \
  "$FLAG_TASK03_B64" \
  "$FLAG_TASK04_PLAINTEXT" \
  "$FLAG_TASK05_FILE" \
  "$FLAG_TASK06_TXT" \
  "$FLAG_TASK07_TX" \
  "$FLAG_TASK08_SECRET" \
  "$FLAG_TASK09_PLAINTEXT")
FLAG_TASK10_EXPECTED="$(printf '%s' "$_flags_concat" | openssl dgst -sha256 -r | awk '{print $1}')"

# ------------------------------------------------------------------------------
# Mentor password
# ------------------------------------------------------------------------------
if [ -n "${CTF_MENTOR_PASSWORD:-}" ]; then
  _mentor_pw="$CTF_MENTOR_PASSWORD"
else
  _mentor_pw="$(rand_triple)"
fi
# SHA-512 crypt via openssl (no extra deps; readable by ctf-reveal C helper via crypt(3))
_mentor_hash="$(openssl passwd -6 "$_mentor_pw")"

# ------------------------------------------------------------------------------
# Write secrets/hub.env (authoritative full map — readable only by root in the hub)
# ------------------------------------------------------------------------------
umask 077
cat > "$SECRETS_DIR/hub.env" <<EOF
# Generated by scripts/generate-flags.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
FLAG_TASK01=$FLAG_TASK01
FLAG_TASK02=$FLAG_TASK02_PORT
FLAG_TASK03=$FLAG_TASK03_B64
FLAG_TASK04=$FLAG_TASK04_PLAINTEXT
FLAG_TASK05=$FLAG_TASK05_FILE
FLAG_TASK06=$FLAG_TASK06_TXT
FLAG_TASK07=$FLAG_TASK07_TX
FLAG_TASK08=$FLAG_TASK08_SECRET
FLAG_TASK09=$FLAG_TASK09_PLAINTEXT
FLAG_TASK10=$FLAG_TASK10_EXPECTED

# Side data the Ink app reads for task descriptions
FLAG_TASK02_PORT=$FLAG_TASK02_PORT
FLAG_TASK06_HOST=$FLAG_TASK06_HOST
EOF
chmod 600 "$SECRETS_DIR/hub.env"

cat > "$SECRETS_DIR/mentor.hash" <<EOF
$_mentor_hash
EOF
chmod 644 "$SECRETS_DIR/mentor.hash"

# ------------------------------------------------------------------------------
# Per-task env slices
# ------------------------------------------------------------------------------
cat > "$SECRETS_DIR/task02.env" <<EOF
FLAG_TASK02_PORT=$FLAG_TASK02_PORT
FLAG_TASK04_PLAINTEXT=$FLAG_TASK04_PLAINTEXT
FLAG_TASK05_SSH_PASS=$FLAG_TASK05_SSH_PASS
EOF

cat > "$SECRETS_DIR/task05.env" <<EOF
FLAG_TASK05_SSH_PASS=$FLAG_TASK05_SSH_PASS
FLAG_TASK05_FILE=$FLAG_TASK05_FILE
EOF

cat > "$SECRETS_DIR/task06.env" <<EOF
FLAG_TASK06_HOST=$FLAG_TASK06_HOST
FLAG_TASK06_TXT=$FLAG_TASK06_TXT
EOF

cat > "$SECRETS_DIR/task07.env" <<EOF
FLAG_TASK07_TX=$FLAG_TASK07_TX
EOF

cat > "$SECRETS_DIR/task08.env" <<EOF
FLAG_TASK08_AUTH_TOKEN=$FLAG_TASK08_AUTH_TOKEN
FLAG_TASK08_SECRET=$FLAG_TASK08_SECRET
EOF

cat > "$SECRETS_DIR/task09.env" <<EOF
FLAG_TASK09_CIPHERTEXT=$FLAG_TASK09_CIPHERTEXT
FLAG_TASK09_KEY=$FLAG_TASK09_KEY
EOF

cat > "$SECRETS_DIR/task10.env" <<EOF
FLAG_TASK10_EXPECTED=$FLAG_TASK10_EXPECTED
EOF

cat > "$SECRETS_DIR/decoys.env" <<EOF
DECOY_NAMES=$DECOY_NAMES
DECOY_COUNT=$DECOY_COUNT
EOF

for f in task02 task05 task06 task07 task08 task09 task10 decoys; do
  chmod 600 "$SECRETS_DIR/$f.env"
done

# ------------------------------------------------------------------------------
# Per-instance compose override: one alpine sleep container per randomized
# decoy. Written alongside the secrets slices so spin-up.sh can pass it to
# `docker compose -f docker-compose.yml -f $SECRETS_DIR/override.yml`.
# Regenerated on every spin-up so the decoy set (and FLAG_TASK01) vary.
# ------------------------------------------------------------------------------
_override="$SECRETS_DIR/override.yml"
{
  echo "# Auto-generated by scripts/generate-flags.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Do not edit by hand — regenerated on every ./spin-up.sh run."
  echo "services:"
  IFS=',' read -r -a _decoy_arr <<< "$DECOY_NAMES"
  for _d in "${_decoy_arr[@]}"; do
    cat <<YML
  ${_d}:
    image: alpine:3.19
    hostname: ${_d}
    command: ["sleep", "infinity"]
    networks:
      ctfnet:
        aliases:
          - ${_d}
YML
  done
} > "$_override"

# Emit the mentor password on stdout so spin-up.sh can capture and print it.
# It is NEVER written to disk in plaintext.
printf 'MENTOR_PASSWORD=%s\n' "$_mentor_pw"
